---
- name: Configure my RHEL working environment
  hosts: workstations
  gather_facts: False
  become: True
  become_method: sudo

  tasks:
    - name: Install tmux, tree, and vim to latest
      yum:
        name:
          - tree
          - tmux
          - vim
        state: latest

    - name: Update bash_profile
      blockinfile:
        create: True
        dest: /home/{{ profile }}/.bash_profile
        block: "{{ lookup('file', 'files/bash_profile') }}"

    - name: Update vimrc
      blockinfile:
        create: True
        dest: /home/{{ profile }}/.vimrc
        marker: '" {mark} ANSIBLE MANAGED BLOCK'
        block: "{{ lookup('file', 'files/vimrc') }}"

    - name: Update tmux.conf
      blockinfile:
        create: True
        dest: /home/{{ profile }}/.tmux.conf
        block: "{{ lookup('file', 'files/tmux.conf') }}"
