---
- name: Configure my RHEL working environment
  hosts: workstations

  tasks:
    - name: Install tmux
      yum:
        name: tmux
        state: latest

    - name: Install tree
      yum:
        name: tree
        state: latest

    - name: Make sure VIM is at latest
      yum:
        name: vim
        state: latest

    - name: Update bash_profile
      blockinfile:
        create: True
        dest: /home/{{ profile }}/.bash_profile
        block: "{{ lookup('file', 'files/bash_profile') }}"

    - name: Update vimrc
      blockinfile:
        create: True
        dest: /home/{{ profile }}/.vimrc
        block: "{{ lookup('file', 'files/vimrc') }}"
