---
- name: Configure my RHEL working environment
  hosts: workstations
  gather_facts: False
  become: True
  become_method: sudo
  tasks:
    - name: Install tmux, tree, and vim to latest
      yum:
        name:
          - tree
          - tmux
          - vim
        state: latest

- name: Update Configuration files
  hosts: workstations
  gather_facts: True
  tasks:
    - name: Update bash_profile
      blockinfile:
        create: True
        dest: "{{ ansible_env.HOME }}/.bash_profile"
        block: "{{ lookup('file', 'files/bash_profile') }}"

    - name: Update vimrc
      blockinfile:
        create: True
        dest: "{{ ansible_env.HOME }}/.vimrc"
        marker: '" {mark} ANSIBLE MANAGED BLOCK'
        block: "{{ lookup('file', 'files/vimrc') }}"

    - name: Update tmux.conf
      blockinfile:
        create: True
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
        block: "{{ lookup('file', 'files/tmux.conf') }}"
